name = "aaac-video-generator"
main = ".open-next/worker.js"
compatibility_date = "2026-03-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
account_id = "d1d6a9d309a1e28b2abf202482b2b7b8"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[kv_namespaces]]
binding = "JOBS_KV"
id = "c04eac495c794f92a377a3f3cd7b3072"
preview_id = "76e79c4e7dcf49e98aa882b92129dd2e"

[vars]
GOOGLE_SHEET_ID = "1hijw2clTvmZV2qxu6u0GnwR8fd1HbbcfbjJRzuvn0Rk"
VIDEO_API_BASE_URL = "https://mediagenerationapi-production.up.railway.app"
