name = "aaac-video-generator"
main = ".open-next/worker.js"
compatibility_date = "2026-03-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
account_id = "bb44c9b37ef496cf4101616fc6c49fd8"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[kv_namespaces]]
binding = "JOBS_KV"
id = "080d843cb45a415a8a43b37e6d840660"
preview_id = "efabd1e4c0af4064b0c5477666944e47"

[vars]
GOOGLE_SHEET_ID = "1hijw2clTvmZV2qxu6u0GnwR8fd1HbbcfbjJRzuvn0Rk"
VIDEO_API_BASE_URL = "https://mediagenerationapi-production.up.railway.app"
